### PR TITLE
final fixes

### PR DESCRIPTION
**Pull request by jujuzitroni**
lots of different little changes and fixes.
please refer to commits :)

### CODE REVIEW

**Review by Dev-dfm — APPROVED** [review]
lgtm 🚀

**Review by l-goede — APPROVED** [review]
lgtm!!!

**Review by lajanzen — APPROVED** [review]
🚀

**Review by Maurizio-F — APPROVED** [review]
lgtm 🚀

**Review by daebert — APPROVED** [review]
LGTM!

**Review by dhnazarenko — COMMENTED** [review]
LGTM 🚀

**Review by l-goede — APPROVED** [review]
Nice!

**Review by Dev-dfm — APPROVED** [review]
lgtm 🚀

**Review by lajanzen — APPROVED** [review]
🚀

**Pull request merged**
